server:
  port: 8762
  
spring:
  application:
    name: service-helloworld

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

logging:
  level:
    root: INFO
