spring:
  application:
    name: cattest                    
  cloud:
    config:
      uri: http://localhost:7001/       
      profile: dev                      
      label: '{cipher}8ed109cf611d1303e082d0e208359f12ee8043b380c1e5b3dfc852a650d8efdb'                    
server:
  port: 7002
management:
  security:
    enabled: false
