spring:
  application:
    name: cattest                    
  cloud:
    config:
      uri: http://localhost:7001/       
      profile: dev                      
      label: '{cipher}45dc5d0afe890ddda094120796505f0f8a4d9ddaa7b6c3d06144153b31c02a25'                    
server:
  port: 7002
management:
  security:
    enabled: false
